### ISSUE TITLE
isValidPat{p, q} should be improved

### ISSUE THREAD

**Issue by jtobin** [urbit/urbit-ob#17]
It would be quite useful to make these fellows perform stronger checks.  See urbit/bridge#48.

**Comment by shrugs** [comment]
adding `require('urbit-ob').isValidPatq('~----')` as a "that probably isn't right" case

**Comment by liam-fitzgerald** [comment]
Given the fairly complex nature of the `@p` algorithm, is there anything wrong with

 `isValidPatp = p => isValidPat(p) && p === patp(patp2dec(p))` and similar for `isValidPatq`

My thinking is that by the time you've written a correct validation algorithm, you've almost written another parser for patps. We could still expose `isValidPat` for weaker/faster checks. Most consumers of urbit-ob (landscape, bridge) want isValidPatp to check user input.

**Comment by jtobin** [comment]
@liam-fitzgerald Yeah that works for me.  I think the fact that one basically needs to write another parser to do proper validation here is why this issue has sat for so long.. 😄

**Comment by jtobin** [comment]
(I've added this locally -- will package it up and push a new version.)
